//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDMDDEA.Language {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResDDEAMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResDDEAMain() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UDMDDEA.Language.ResDDEAMain", typeof(ResDDEAMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [오류]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddMessage_Message {
            get {
                return ResourceManager.GetString("AddMessage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   평균 속도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_AverageSpeed {
            get {
                return ResourceManager.GetString("FrmMain_AverageSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 접점확인을 위한 PLC 연결 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_bConnected_fail {
            get {
                return ResourceManager.GetString("FrmMain_bConnected_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 접점확인을 위한 PLC 연결 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_bConnected_ok {
            get {
                return ResourceManager.GetString("FrmMain_bConnected_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 접점확인을 위한 통신설정 확인요구과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CheckConnectSymbolTest_Exception_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_CheckConnectSymbolTest_Exception_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 파라미터 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CheckConnectSymbolTest_Exception_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_CheckConnectSymbolTest_Exception_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 최대Size ({1})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CheckConnectSymbolTest_Exception_Msg3 {
            get {
                return ResourceManager.GetString("FrmMain_CheckConnectSymbolTest_Exception_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 접점확인을 위한 통신연결 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CheckConnectSymbolTest_Exception_Msg4 {
            get {
                return ResourceManager.GetString("FrmMain_CheckConnectSymbolTest_Exception_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 접점확인을 위한 PLC 연결 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CheckConnectSymbolTest_fail {
            get {
                return ResourceManager.GetString("FrmMain_CheckConnectSymbolTest_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 접점확인을 위한 수집 불가 접점 (과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CheckConnectSymbolTest_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_CheckConnectSymbolTest_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 접점확인을 위한 수집 불가 접점 갯수 :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CheckConnectSymbolTest_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_CheckConnectSymbolTest_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 접점확인을 위한 전체 접점수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CheckConnectSymbolTest_Msg3 {
            get {
                return ResourceManager.GetString("FrmMain_CheckConnectSymbolTest_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 수집대상 접점수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CheckConnectSymbolTest_Msg4 {
            get {
                return ResourceManager.GetString("FrmMain_CheckConnectSymbolTest_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 접점확인을 위한 통신 설정 확인 요구과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CheckConnectSymbolTest_Msg5 {
            get {
                return ResourceManager.GetString("FrmMain_CheckConnectSymbolTest_Msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 파라미터 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CheckConnectSymbolTest_Msg6 {
            get {
                return ResourceManager.GetString("FrmMain_CheckConnectSymbolTest_Msg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 최대Size ({1})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CheckConnectSymbolTest_Msg7 {
            get {
                return ResourceManager.GetString("FrmMain_CheckConnectSymbolTest_Msg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 접점확인을 위한 통신 연결 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CheckConnectSymbolTest_Msg8 {
            get {
                return ResourceManager.GetString("FrmMain_CheckConnectSymbolTest_Msg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 접점확인을 위한 PLC 연결 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CheckConnectSymbolTest_ok {
            get {
                return ResourceManager.GetString("FrmMain_CheckConnectSymbolTest_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 통신설정 연결 실패 -&gt; 프로젝트 파일을 읽지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CheckConnectTest_fail {
            get {
                return ResourceManager.GetString("FrmMain_CheckConnectTest_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CheckConnectTest 실패
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CheckConnectTest_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_CheckConnectTest_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 현재 통신 설정으로 접속이 불가합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CheckConnectTest_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_CheckConnectTest_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CheckConnectTest 성공
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CheckConnectTest_Msg3 {
            get {
                return ResourceManager.GetString("FrmMain_CheckConnectTest_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SetDDEAProjectForManager 진입 전
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CheckConnectTest_Msg4 {
            get {
                return ResourceManager.GetString("FrmMain_CheckConnectTest_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 프로젝트를 열수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CheckConnectTest_Msg5 {
            get {
                return ResourceManager.GetString("FrmMain_CheckConnectTest_Msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 통신설정 연결 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CheckConnectTest_ok {
            get {
                return ResourceManager.GetString("FrmMain_CheckConnectTest_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재까지 기록된 메세지를 지웁니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_ClearText {
            get {
                return ResourceManager.GetString("FrmMain_ClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   강제 종료되므로 수집 중에 사용을 유의해야 함.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_Close {
            get {
                return ResourceManager.GetString("FrmMain_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 정지 중 모드가 변경 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_collecModeType_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_collecModeType_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   부분수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CollectMode_txt1 {
            get {
                return ResourceManager.GetString("FrmMain_CollectMode_txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   필터수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CollectMode_txt2 {
            get {
                return ResourceManager.GetString("FrmMain_CollectMode_txt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   출력수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CollectMode_txt3 {
            get {
                return ResourceManager.GetString("FrmMain_CollectMode_txt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CollectMode_txt4 {
            get {
                return ResourceManager.GetString("FrmMain_CollectMode_txt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOB수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CollectMode_txt5 {
            get {
                return ResourceManager.GetString("FrmMain_CollectMode_txt5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파라미터수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CollectMode_txt6 {
            get {
                return ResourceManager.GetString("FrmMain_CollectMode_txt6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CollectModeType_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_CollectModeType_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모드로 변경되어 수집 정지함.  이전모드 :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CollectModeType_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_CollectModeType_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_ConfigUSB_txt1 {
            get {
                return ResourceManager.GetString("FrmMain_ConfigUSB_txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CCLink 통신설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_ConfigUSB_txt2 {
            get {
                return ResourceManager.GetString("FrmMain_ConfigUSB_txt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CCLink 설정이 아닙니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_ConfigUSB_txt3 {
            get {
                return ResourceManager.GetString("FrmMain_ConfigUSB_txt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   통신설정 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_ConfigUSB_txt4 {
            get {
                return ResourceManager.GetString("FrmMain_ConfigUSB_txt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모드 변경 접수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_ConfigUSB_txt5 {
            get {
                return ResourceManager.GetString("FrmMain_ConfigUSB_txt5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 접점확인을 위한 대상접점수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_ctagListCount_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_ctagListCount_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 수집대상 접점수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_ctagListCount_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_ctagListCount_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 필터 후 수집접점 수(인덱스처리) : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_cTotalSymbolListCount_Msg {
            get {
                return ResourceManager.GetString("FrmMain_cTotalSymbolListCount_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System 메세지 출력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CurrentMessage {
            get {
                return ResourceManager.GetString("FrmMain_CurrentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 Recipe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CurrentRecipe {
            get {
                return ResourceManager.GetString("FrmMain_CurrentRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 속도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CurrentSpeed {
            get {
                return ResourceManager.GetString("FrmMain_CurrentSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cycle 종료 조건과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CycleEndTitle {
            get {
                return ResourceManager.GetString("FrmMain_CycleEndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cycle 최대 시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CycleMaxTime {
            get {
                return ResourceManager.GetString("FrmMain_CycleMaxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cycle 최소 시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CycleMinTime {
            get {
                return ResourceManager.GetString("FrmMain_CycleMinTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cycle 반복 횟수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CycleNumber {
            get {
                return ResourceManager.GetString("FrmMain_CycleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cycle 시작 조건과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CycleStartTitle {
            get {
                return ResourceManager.GetString("FrmMain_CycleStartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cycle  (현재/전체)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CycleTitle {
            get {
                return ResourceManager.GetString("FrmMain_CycleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cycle 제외 조건과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_CycleTrigger {
            get {
                return ResourceManager.GetString("FrmMain_CycleTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 수신 문제(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_DoProfilerCommand_Exception {
            get {
                return ResourceManager.GetString("FrmMain_DoProfilerCommand_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 수집 시작 명령 접수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_DoProfilerCommand_txt1 {
            get {
                return ResourceManager.GetString("FrmMain_DoProfilerCommand_txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 수집 정지 명령 접수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_DoProfilerCommand_txt2 {
            get {
                return ResourceManager.GetString("FrmMain_DoProfilerCommand_txt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 프로젝트 열기에 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_DoProfilerCommand_txt3 {
            get {
                return ResourceManager.GetString("FrmMain_DoProfilerCommand_txt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] UPM 파일에 Cycle 설정 오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_EMCollectMode_Error_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_EMCollectMode_Error_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 수집 불가 접점 분석 중 통신 상태 문제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_EMCollectMode_Error_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_EMCollectMode_Error_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 필터수집 패킷이 없습니다. 수집 설정을 확인해 주십시오.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_EMCollectModeFilterNormal_Msg {
            get {
                return ResourceManager.GetString("FrmMain_EMCollectModeFilterNormal_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 필터수집 Bundle 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_EMCollectModeFilterNormal_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_EMCollectModeFilterNormal_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] LOB수집 Bundle 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_EMCollectModeLOB_Msg {
            get {
                return ResourceManager.GetString("FrmMain_EMCollectModeLOB_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 부분수집 패킷이 없습니다. 수집 설정을 확인해 주십시오.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_EMCollectModeNormal_Msg {
            get {
                return ResourceManager.GetString("FrmMain_EMCollectModeNormal_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 부분수집 Bundle 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_EMCollectModeNormal_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_EMCollectModeNormal_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 파라미터 수집 패킷이 없습니다. 수집 설정을 확인해 주십시오.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_EMCollectModeParameterNormal_Msg {
            get {
                return ResourceManager.GetString("FrmMain_EMCollectModeParameterNormal_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 파라미터 수집 Bundle 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_EMCollectModeParameterNormal_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_EMCollectModeParameterNormal_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 기준출력수집 Bundle 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_EMCollectModeStandardCoil_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_EMCollectModeStandardCoil_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 전체수집 Bundle 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_EMCollectModeStandardCoil_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_EMCollectModeStandardCoil_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_EMCollectmodeWait_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_EMCollectmodeWait_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모드로 변경되어 수집 정지함.  이전모드 :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_EMCollectmodeWait_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_EMCollectmodeWait_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류]설정정보가 충분치 않아 현재 수집모드로 진행할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_EMConnectAppTypeManager_Msg {
            get {
                return ResourceManager.GetString("FrmMain_EMConnectAppTypeManager_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류]설정정보가 충분치 않아 현재 수집모드로 진행할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_EMConnectAppTypeProfiler_Msg {
            get {
                return ResourceManager.GetString("FrmMain_EMConnectAppTypeProfiler_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 초기 설정에 문제가 있습니다.  과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_ExcuteInitialMode_Exception {
            get {
                return ResourceManager.GetString("FrmMain_ExcuteInitialMode_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 수집 불가 접점 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_FailAddress_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_FailAddress_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _수집 불가 접점_과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_FailAddress_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_FailAddress_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ------------수집 불가 접점 리스트-----------
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_FailAddress_Msg3 {
            get {
                return ResourceManager.GetString("FrmMain_FailAddress_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 접점 리스트에 미등록 접점 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_FailAddress_Msg4 {
            get {
                return ResourceManager.GetString("FrmMain_FailAddress_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 파라메터 파일 변경 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_FileChanged_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_FileChanged_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] UPM 파일 변경 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_FileChanged_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_FileChanged_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 설정 파일 변경 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_FileChanged_Msg3 {
            get {
                return ResourceManager.GetString("FrmMain_FileChanged_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 필터링 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_FilterAndPrepareNormalModeForManager_Start {
            get {
                return ResourceManager.GetString("FrmMain_FilterAndPrepareNormalModeForManager_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 필터링 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_FilteringStart {
            get {
                return ResourceManager.GetString("FrmMain_FilteringStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 부분/필터수집 Bundle 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_FilterNormalBundleList_Msg {
            get {
                return ResourceManager.GetString("FrmMain_FilterNormalBundleList_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 필터 수집 완료 정지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_FilterNormalComp {
            get {
                return ResourceManager.GetString("FrmMain_FilterNormalComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 메모리 정리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_FlushMemory {
            get {
                return ResourceManager.GetString("FrmMain_FlushMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   완료 예정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_IblTime_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_IblTime_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시작 시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_IblTime_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_IblTime_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 기준 Recipe : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_lblBaseRecipe_Msg {
            get {
                return ResourceManager.GetString("FrmMain_lblBaseRecipe_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_lblBaseRecipe_Text1 {
            get {
                return ResourceManager.GetString("FrmMain_lblBaseRecipe_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] UPM 파일 열기 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_lblBaseRecipe_Text2 {
            get {
                return ResourceManager.GetString("FrmMain_lblBaseRecipe_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 기준출력수집 Bundle 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_lblBaseRecipeBundle_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_lblBaseRecipeBundle_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 전체수집 Bundle 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_lblBaseRecipeBundle_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_lblBaseRecipeBundle_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] LOB수집 Bundle 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_LOBBundleList_Msg {
            get {
                return ResourceManager.GetString("FrmMain_LOBBundleList_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] LS 통신설정 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_LSConfig_txt {
            get {
                return ResourceManager.GetString("FrmMain_LSConfig_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Machine 명 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_MachineName {
            get {
                return ResourceManager.GetString("FrmMain_MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 저장할 로그 폴더 위치 전송과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_MainPath {
            get {
                return ResourceManager.GetString("FrmMain_MainPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 접점확인을 위한 대상접점수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_MakeChekcedTagList_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_MakeChekcedTagList_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 접점확인을 위한 전체 접점수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_MakeChekcedTagList_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_MakeChekcedTagList_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 수집대상 접점수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_MakeChekcedTagList_Msg3 {
            get {
                return ResourceManager.GetString("FrmMain_MakeChekcedTagList_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 접점확인을 위한 수집불가접점 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_MakeChekcedTagList_Msg4 {
            get {
                return ResourceManager.GetString("FrmMain_MakeChekcedTagList_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 접점확인을 위한 전체 접점수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_MakeChekcedTagList_Msg5 {
            get {
                return ResourceManager.GetString("FrmMain_MakeChekcedTagList_Msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 수집대상 접점수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_MakeChekcedTagList_Msg6 {
            get {
                return ResourceManager.GetString("FrmMain_MakeChekcedTagList_Msg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SetConfigFile (Config 파일 열기) 실패
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_ManegerMode_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_ManegerMode_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최대 속도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_MaxSpeed {
            get {
                return ResourceManager.GetString("FrmMain_MaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수집 상태 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_Monitor {
            get {
                return ResourceManager.GetString("FrmMain_Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수집 상태과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_MonitorInfo {
            get {
                return ResourceManager.GetString("FrmMain_MonitorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 수집중 종료 할 수 없음.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_Msg_Close1 {
            get {
                return ResourceManager.GetString("FrmMain_Msg_Close1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정상종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_Msg_Close2 {
            get {
                return ResourceManager.GetString("FrmMain_Msg_Close2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테스트 모드로 실행중입니다.!! 디버깅하시러면 VS2008과 연결해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_Msg_Load1 {
            get {
                return ResourceManager.GetString("FrmMain_Msg_Load1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수집 머신 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_Msg_Load2 {
            get {
                return ResourceManager.GetString("FrmMain_Msg_Load2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manager에서 설정된 내용이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_Msg_Load3 {
            get {
                return ResourceManager.GetString("FrmMain_Msg_Load3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 현재 수집 모드 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_Msg_Load4 {
            get {
                return ResourceManager.GetString("FrmMain_Msg_Load4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 수집 모드 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_Msg_Load5 {
            get {
                return ResourceManager.GetString("FrmMain_Msg_Load5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_None {
            get {
                return ResourceManager.GetString("FrmMain_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 필터 후 Packet 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_NormalBundleListCount_Msg {
            get {
                return ResourceManager.GetString("FrmMain_NormalBundleListCount_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 필터 후 수집접점 수(인덱스처리) : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_NormalPackerSClear_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_NormalPackerSClear_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 필터 후 Packet 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_NormalPackerSClear_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_NormalPackerSClear_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수집된 파일 경로를 엽니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_Open {
            get {
                return ResourceManager.GetString("FrmMain_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DDEA의 PLC 통신 설정을 보여주는 창을 엽니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_Open_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_Open_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수집 대상 Symbol 내용을 보여주는 창을 엽니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_Open_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_Open_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 파라미터 파일 열기 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_OpenParaFileForManager_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_OpenParaFileForManager_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 파라미터 열기 아이템 오류(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_OpenParaFileForManager_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_OpenParaFileForManager_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Param 아이템 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_OpenParaFileForManager_Msg3 {
            get {
                return ResourceManager.GetString("FrmMain_OpenParaFileForManager_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 파일 열기 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_OpenParaFileForManager_Msg4 {
            get {
                return ResourceManager.GetString("FrmMain_OpenParaFileForManager_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 파라미터 열기 아이템 오류(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_OpenParaFileForManager_Msg5 {
            get {
                return ResourceManager.GetString("FrmMain_OpenParaFileForManager_Msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MDC 중복 심볼  : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_OpenParaFileForManager_Msg6 {
            get {
                return ResourceManager.GetString("FrmMain_OpenParaFileForManager_Msg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Packet (현재/전체)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_PackerTitle {
            get {
                return ResourceManager.GetString("FrmMain_PackerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] LOB 모드 수집 중 파라메터 파일 변경 요청과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_paramFileChanged_Msg {
            get {
                return ResourceManager.GetString("FrmMain_paramFileChanged_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] PLC Maker : Mitsubishi과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_PLCMaker1 {
            get {
                return ResourceManager.GetString("FrmMain_PLCMaker1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] PLC Maker : LS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_PLCMaker2 {
            get {
                return ResourceManager.GetString("FrmMain_PLCMaker2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 서버 연결 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_ProfilerMode_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_ProfilerMode_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 서버 연결 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_ProfilerMode_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_ProfilerMode_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 프로젝트 이름 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_ProjectName {
            get {
                return ResourceManager.GetString("FrmMain_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 프로젝트 경로 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_ProjectPath {
            get {
                return ResourceManager.GetString("FrmMain_ProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipe 주소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_RecipeAddress {
            get {
                return ResourceManager.GetString("FrmMain_RecipeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Recipe 변경으로 수집 대기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_RecipeErr {
            get {
                return ResourceManager.GetString("FrmMain_RecipeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류]  Recipe값을 읽을수 없어 정지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_RecipeNFD {
            get {
                return ResourceManager.GetString("FrmMain_RecipeNFD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재수집 시도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_Reconnect_State {
            get {
                return ResourceManager.GetString("FrmMain_Reconnect_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 수집 시작 분석 중 문제 발생과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_Run_Exception {
            get {
                return ResourceManager.GetString("FrmMain_Run_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수집 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_Run_State {
            get {
                return ResourceManager.GetString("FrmMain_Run_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   필터수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_sCollectMode_FilterCollect {
            get {
                return ResourceManager.GetString("FrmMain_sCollectMode_FilterCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   부분수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_sCollectMode_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_sCollectMode_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   필터수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_sCollectMode_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_sCollectMode_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   부분수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_sCollectMode_NormalCollect {
            get {
                return ResourceManager.GetString("FrmMain_sCollectMode_NormalCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파라미터수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_sCollectMode_ParameterCollect {
            get {
                return ResourceManager.GetString("FrmMain_sCollectMode_ParameterCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 설정 파일 열기 시도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SetConfigFile_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_SetConfigFile_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 설정 파일 열기 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SetConfigFile_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_SetConfigFile_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SetConfigFile_Msg3 {
            get {
                return ResourceManager.GetString("FrmMain_SetConfigFile_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///     의 통신 설정 없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SetConfigFile_Msg4 {
            get {
                return ResourceManager.GetString("FrmMain_SetConfigFile_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 설정 파일 열기 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SetConfigFile_Msg5 {
            get {
                return ResourceManager.GetString("FrmMain_SetConfigFile_Msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] UPM 파일 열기 시도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SetDDEAProjectForManager_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_SetDDEAProjectForManager_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DDEAManager 실행 후 Profiler 프로젝트로 열기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SetDDEAProjectForManager_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_SetDDEAProjectForManager_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] UPM 파일 열기 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SetDDEAProjectForManager_Msg3 {
            get {
                return ResourceManager.GetString("FrmMain_SetDDEAProjectForManager_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] UPM 파일에 Cycle 설정 오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SetDDEAProjectForManager_Msg4 {
            get {
                return ResourceManager.GetString("FrmMain_SetDDEAProjectForManager_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 수집 불가 접점 분석 중 통신상태 문제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SetDDEAProjectForManager_Msg5 {
            get {
                return ResourceManager.GetString("FrmMain_SetDDEAProjectForManager_Msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 수집불가 접점 개수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SetDDEAProjectForManager_Msg6 {
            get {
                return ResourceManager.GetString("FrmMain_SetDDEAProjectForManager_Msg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _수집 불가 접점_과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SetDDEAProjectForManager_Msg7 {
            get {
                return ResourceManager.GetString("FrmMain_SetDDEAProjectForManager_Msg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ------------수집 불가 접점 리스트-----------
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SetDDEAProjectForManager_Msg8 {
            get {
                return ResourceManager.GetString("FrmMain_SetDDEAProjectForManager_Msg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 접점 리스트에 미등록 접점 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SetDDEAProjectForManager_Msg9 {
            get {
                return ResourceManager.GetString("FrmMain_SetDDEAProjectForManager_Msg9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 통신설정 연결 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SetDDEAProjectForManagerTest_ok {
            get {
                return ResourceManager.GetString("FrmMain_SetDDEAProjectForManagerTest_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] UPM 파일 열기 시도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SetDDEAProjectFromProfiler_Msg_UPM1 {
            get {
                return ResourceManager.GetString("FrmMain_SetDDEAProjectFromProfiler_Msg_UPM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] UPM 파일 열기 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SetDDEAProjectFromProfiler_Msg_UPM2 {
            get {
                return ResourceManager.GetString("FrmMain_SetDDEAProjectFromProfiler_Msg_UPM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Cycle 기준 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SetFagCycleInfo_Msg {
            get {
                return ResourceManager.GetString("FrmMain_SetFagCycleInfo_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Cycle 기준 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SetFragCycleInfo_Msg {
            get {
                return ResourceManager.GetString("FrmMain_SetFragCycleInfo_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수집 속도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SpeedTitle {
            get {
                return ResourceManager.GetString("FrmMain_SpeedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 기준수집 Bundle 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_StandardPackerBundle_Msg {
            get {
                return ResourceManager.GetString("FrmMain_StandardPackerBundle_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 기준수집 Bundle 수: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_StandardPacketS_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_StandardPacketS_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 기준 Recipe : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_StandardPacketS_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_StandardPacketS_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기준 Recipe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_StandardRecipe {
            get {
                return ResourceManager.GetString("FrmMain_StandardRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 확인을 위한 textbox
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SubData {
            get {
                return ResourceManager.GetString("FrmMain_SubData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   창을 Tray에서 뺍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SubtractWindow {
            get {
                return ResourceManager.GetString("FrmMain_SubtractWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시스템 메시지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_SystemMessage {
            get {
                return ResourceManager.GetString("FrmMain_SystemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수집 시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_TimeTitle {
            get {
                return ResourceManager.GetString("FrmMain_TimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_tmrRegCheck_Tick_Exception_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_tmrRegCheck_Tick_Exception_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    모드전환시 문제 발생(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_tmrRegCheck_Tick_Exception_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_tmrRegCheck_Tick_Exception_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 실행함수 동작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_tmrRun_txt {
            get {
                return ResourceManager.GetString("FrmMain_tmrRun_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수집 기준 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_TpgMaster {
            get {
                return ResourceManager.GetString("FrmMain_TpgMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 초기화 중 오류 발생과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_TrackerMode_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_TrackerMode_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Tracker 모드로 진입했습니다.
        ///새로운 프로젝트가 생성됐습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_TrackerMode_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_TrackerMode_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 현재 수집 대상 리스트가 없습니다. 설정해 주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_TrackerMode_Msg3 {
            get {
                return ResourceManager.GetString("FrmMain_TrackerMode_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수집 조건과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_UcCycleTitle {
            get {
                return ResourceManager.GetString("FrmMain_UcCycleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기준 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_UcMachineTitle {
            get {
                return ResourceManager.GetString("FrmMain_UcMachineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] UPM 파일이 변경되어 정지함. 대기모드:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_upmFileChanged_Msg1 {
            get {
                return ResourceManager.GetString("FrmMain_upmFileChanged_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   , 이전모드 :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_upmFileChanged_Msg2 {
            get {
                return ResourceManager.GetString("FrmMain_upmFileChanged_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   창을 Tray로 내립니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_WindowDown1 {
            get {
                return ResourceManager.GetString("FrmMain_WindowDown1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLC Connectiong 끊김으로 인해 수집 종료합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_WriteLog1 {
            get {
                return ResourceManager.GetString("FrmMain_WriteLog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error 인해 수집을 종료합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FrmMain_WriteLog2 {
            get {
                return ResourceManager.GetString("FrmMain_WriteLog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메세지 기록이 삭제됩니다.
        ///내용을 복사하려면 Ctrl + A로 전체 선택 후 복사하여 메모장을 이용하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mnuClear_Msg_Click2 {
            get {
                return ResourceManager.GetString("mnuClear_Msg_Click2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   강제 종료 됩니다
        ///수행 중인 Log 정보가 일부 기록되지 않을 수 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mnuClose_Msg_Click1 {
            get {
                return ResourceManager.GetString("mnuClose_Msg_Click1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 통신 설정 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mnuConnection_Msg_Click {
            get {
                return ResourceManager.GetString("mnuConnection_Msg_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 새로운 프로젝트 생성과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mnuNew__Msg_Click {
            get {
                return ResourceManager.GetString("mnuNew__Msg_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 프로젝트 불러오기 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mnuOpen_Msg_Click1 {
            get {
                return ResourceManager.GetString("mnuOpen_Msg_Click1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 프로젝트 불러오기 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mnuOpen_Msg_Click2 {
            get {
                return ResourceManager.GetString("mnuOpen_Msg_Click2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 프로젝트 저장 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mnuSave_Msg_Click1 {
            get {
                return ResourceManager.GetString("mnuSave_Msg_Click1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 프로젝트 저장 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mnuSave_Msg_Click2 {
            get {
                return ResourceManager.GetString("mnuSave_Msg_Click2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 현재 통신 설정으로 접속이 불가하여 시작할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mnuStart_Msg_Click {
            get {
                return ResourceManager.GetString("mnuStart_Msg_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 정지 중 입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tmrCollectRunCheck_Msg_Tick1 {
            get {
                return ResourceManager.GetString("tmrCollectRunCheck_Msg_Tick1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 모드변경 완료 시작 명령을 시도합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tmrCollectRunCheck_Msg_Tick2 {
            get {
                return ResourceManager.GetString("tmrCollectRunCheck_Msg_Tick2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새로운 파일을 생성합니다.(주기 1시간)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tmrSystemLog_Msg_Tick1 {
            get {
                return ResourceManager.GetString("tmrSystemLog_Msg_Tick1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이전 파일 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tmrSystemLog_Msg_Tick2 {
            get {
                return ResourceManager.GetString("tmrSystemLog_Msg_Tick2", resourceCulture);
            }
        }
    }
}
