//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDM.DDEA.Language {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResDDEA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResDDEA() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UDM.DDEA.Language.ResDDEA", typeof(ResDDEA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   메세지 오류 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CAsyncTcpClient_AnalyzeProfilerMessage_Msg {
            get {
                return ResourceManager.GetString("CAsyncTcpClient_AnalyzeProfilerMessage_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결 실패 재접속 시도 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CAsyncTcpClient_BeginConnect_Msg {
            get {
                return ResourceManager.GetString("CAsyncTcpClient_BeginConnect_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전송 에러 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CAsyncTcpClient_BeginSend_Msg {
            get {
                return ResourceManager.GetString("CAsyncTcpClient_BeginSend_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버로 접속 성공 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CAsyncTcpClient_ConnectCallBack_Msg1 {
            get {
                return ResourceManager.GetString("CAsyncTcpClient_ConnectCallBack_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버로 접속 실패 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CAsyncTcpClient_ConnectCallBack_Msg2 {
            get {
                return ResourceManager.GetString("CAsyncTcpClient_ConnectCallBack_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메세지 분석 실패 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CAsyncTcpClient_OnReceiveCallBack_Msg1 {
            get {
                return ResourceManager.GetString("CAsyncTcpClient_OnReceiveCallBack_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버 연결이 끊겼습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CAsyncTcpClient_OnReceiveCallBack_Msg2 {
            get {
                return ResourceManager.GetString("CAsyncTcpClient_OnReceiveCallBack_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결이 끊겼습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CAsyncTcpServer_Receive_Msg {
            get {
                return ResourceManager.GetString("CAsyncTcpServer_Receive_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전송 에러 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CAsyncTcpServer_SendClientMessage_Msg {
            get {
                return ResourceManager.GetString("CAsyncTcpServer_SendClientMessage_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Cycle 종료(시간범위 정상)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_bCycleEnd_TimeOut_false {
            get {
                return ResourceManager.GetString("CDDEAGroup_bCycleEnd_TimeOut_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Cycle 종료(시간범위 이상)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_bCycleEnd_TimeOut_true {
            get {
                return ResourceManager.GetString("CDDEAGroup_bCycleEnd_TimeOut_true", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Cycle 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_bCycleStart {
            get {
                return ResourceManager.GetString("CDDEAGroup_bCycleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   초기 프로젝트 분석에 문제가 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_BeforeRun_Msg1 {
            get {
                return ResourceManager.GetString("CDDEAGroup_BeforeRun_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LogWrite 시작 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_BeforeRun_Msg2 {
            get {
                return ResourceManager.GetString("CDDEAGroup_BeforeRun_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 초기 프로젝트 분석오류 (과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_BrforeRunCollectMode_Exception_Msg {
            get {
                return ResourceManager.GetString("CDDEAGroup_BrforeRunCollectMode_Exception_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 Recipe : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_cCurrentpacketData_CurrentRecipe {
            get {
                return ResourceManager.GetString("CDDEAGroup_cCurrentpacketData_CurrentRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipe 주소를 찾을 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_cCurrentpacketData_NotfoundRecipe {
            get {
                return ResourceManager.GetString("CDDEAGroup_cCurrentpacketData_NotfoundRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipe 대기중... 현재 레시피: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_cCurrentpacketData_RecipeWait {
            get {
                return ResourceManager.GetString("CDDEAGroup_cCurrentpacketData_RecipeWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///    접점 동작안됨)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_ContactInoperate {
            get {
                return ResourceManager.GetString("CDDEAGroup_ContactInoperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    접점 동작됨)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_ContactOperate {
            get {
                return ResourceManager.GetString("CDDEAGroup_ContactOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 Recipe : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_cPackerData_CurrentRecipe {
            get {
                return ResourceManager.GetString("CDDEAGroup_cPackerData_CurrentRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 Recipe : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_cPackerData_CurrentRecipe1 {
            get {
                return ResourceManager.GetString("CDDEAGroup_cPackerData_CurrentRecipe1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipe 주소를 찾을 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_cPackerData_NotfoundRecipe {
            get {
                return ResourceManager.GetString("CDDEAGroup_cPackerData_NotfoundRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipe 대기중... 현재 레시피: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_cPackerData_RecipeWait {
            get {
                return ResourceManager.GetString("CDDEAGroup_cPackerData_RecipeWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipe 변경으로 인해 초기값을 남기고 Cycle을 변경합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_cPacketData_CycleChanged {
            get {
                return ResourceManager.GetString("CDDEAGroup_cPacketData_CycleChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   패킷의 초기값을 남깁니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_cPacketData_PacketLeave {
            get {
                return ResourceManager.GetString("CDDEAGroup_cPacketData_PacketLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기준출력 수집 모드에서 수집할때 Recipe와 달라 대기합니다.(로그를 저장 안함)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_cPacketData_RecipeDifferent_Msg1 {
            get {
                return ResourceManager.GetString("CDDEAGroup_cPacketData_RecipeDifferent_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipe 대기중... 현재 레시피: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_cPacketData_RecipeWait {
            get {
                return ResourceManager.GetString("CDDEAGroup_cPacketData_RecipeWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {1} 조합 후 Word수(필터제외) : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_DoEvents_Format1 {
            get {
                return ResourceManager.GetString("CDDEAGroup_DoEvents_Format1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   필터된 접점 수 : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_DoEvents_Format2 {
            get {
                return ResourceManager.GetString("CDDEAGroup_DoEvents_Format2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {1} 필터수집 조합 후 Word수(필터제외) : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_DoEvents_Format3 {
            get {
                return ResourceManager.GetString("CDDEAGroup_DoEvents_Format3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   필터된 접점 수 : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_DoEvents_Format4 {
            get {
                return ResourceManager.GetString("CDDEAGroup_DoEvents_Format4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] Cycle 분석 중 오류 발생( 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_DoFragmentCycleProcess_Exception_Msg {
            get {
                return ResourceManager.GetString("CDDEAGroup_DoFragmentCycleProcess_Exception_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] Cycle Check Error 발생 (과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_DoFragmentMasterCycleProcess_Exception_Msg {
            get {
                return ResourceManager.GetString("CDDEAGroup_DoFragmentMasterCycleProcess_Exception_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 전체수집의 기준 데이터 분석 중 오류 ( 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_DoFragmentMasterProces_Exception_Msg {
            get {
                return ResourceManager.GetString("CDDEAGroup_DoFragmentMasterProces_Exception_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 수집 분석 중 문제 발생과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_DoThreadWork_Exception_Msg {
            get {
                return ResourceManager.GetString("CDDEAGroup_DoThreadWork_Exception_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체수집 Word Size : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_EMCollctModeFrag_Format1 {
            get {
                return ResourceManager.GetString("CDDEAGroup_EMCollctModeFrag_Format1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기준수집 Word Size : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_EMCollctModeFrag_Format2 {
            get {
                return ResourceManager.GetString("CDDEAGroup_EMCollctModeFrag_Format2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 전체/출력수집 번들 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_EMCollctModeFrag_Msg1 {
            get {
                return ResourceManager.GetString("CDDEAGroup_EMCollctModeFrag_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOB수집 조합 후 Word수(필터제외) : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_EMCollectModeLOB_Format1 {
            get {
                return ResourceManager.GetString("CDDEAGroup_EMCollectModeLOB_Format1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   부분수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_EMCollectModeNormal_Msg {
            get {
                return ResourceManager.GetString("CDDEAGroup_EMCollectModeNormal_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파라미터 수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_EMCollectmodeParameterNormal_Msg {
            get {
                return ResourceManager.GetString("CDDEAGroup_EMCollectmodeParameterNormal_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 필터 수집 번들 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_FilterNormalBundleListCount_Msg {
            get {
                return ResourceManager.GetString("CDDEAGroup_FilterNormalBundleListCount_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인덱스 심볼을 찾을 수 없음 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_IndexSymbolNone {
            get {
                return ResourceManager.GetString("CDDEAGroup_IndexSymbolNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_Info {
            get {
                return ResourceManager.GetString("CDDEAGroup_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] IOT(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_IOT_Error {
            get {
                return ResourceManager.GetString("CDDEAGroup_IOT_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   부분수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_IOT_ErrorLogWriteTextFile_Msg1 {
            get {
                return ResourceManager.GetString("CDDEAGroup_IOT_ErrorLogWriteTextFile_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _수집 불가접점_과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_IOT_ErrorLogWriteTextFile_Msg2 {
            get {
                return ResourceManager.GetString("CDDEAGroup_IOT_ErrorLogWriteTextFile_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ] 수집 불가 접점 리스트-----------
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_IOT_ErrorLogWriteTextFile_Msg3 {
            get {
                return ResourceManager.GetString("CDDEAGroup_IOT_ErrorLogWriteTextFile_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ) 수집 대상 불가 접점 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_IOT_ErrorLogWriteTextFile_Msg4 {
            get {
                return ResourceManager.GetString("CDDEAGroup_IOT_ErrorLogWriteTextFile_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ) 수집 대상 불가 접점 로그 생성 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_IOT_ErrorLogWriteTextFile_Msg5 {
            get {
                return ResourceManager.GetString("CDDEAGroup_IOT_ErrorLogWriteTextFile_Msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] IOT(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_IOT_Info {
            get {
                return ResourceManager.GetString("CDDEAGroup_IOT_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ) 정보 설정 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_IOT_IotConnection_Msg1 {
            get {
                return ResourceManager.GetString("CDDEAGroup_IOT_IotConnection_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ) 통신 연결 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_IOT_IotConnection_Msg2 {
            get {
                return ResourceManager.GetString("CDDEAGroup_IOT_IotConnection_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ) 통신 연결 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_IOT_IotConnection_Msg3 {
            get {
                return ResourceManager.GetString("CDDEAGroup_IOT_IotConnection_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ) 통신 연결 해제 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_IOT_IotDisconnect_Msg1 {
            get {
                return ResourceManager.GetString("CDDEAGroup_IOT_IotDisconnect_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ) 통신 연결 해제 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_IOT_IotDisconnect_Msg2 {
            get {
                return ResourceManager.GetString("CDDEAGroup_IOT_IotDisconnect_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ) 모니터링 해제 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_IOT_IotDisconnect_Msg3 {
            get {
                return ResourceManager.GetString("CDDEAGroup_IOT_IotDisconnect_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ) 모니터링 해제 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_IOT_IotDisconnect_Msg4 {
            get {
                return ResourceManager.GetString("CDDEAGroup_IOT_IotDisconnect_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ) 모니터링 연결 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_IOT_StartIotMonitor_Msg1 {
            get {
                return ResourceManager.GetString("CDDEAGroup_IOT_StartIotMonitor_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ) 모니터링 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_IOT_StartIotMonitor_Msg2 {
            get {
                return ResourceManager.GetString("CDDEAGroup_IOT_StartIotMonitor_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ) 모니터링 연결 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_IOT_StartIotMonitor_Msg3 {
            get {
                return ResourceManager.GetString("CDDEAGroup_IOT_StartIotMonitor_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] LOB수집 번들 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_LOBBundleListCount_Msg {
            get {
                return ResourceManager.GetString("CDDEAGroup_LOBBundleListCount_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    접점 동작안됨)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_LS_ContactInoperate {
            get {
                return ResourceManager.GetString("CDDEAGroup_LS_ContactInoperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    접점 동작됨)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_LS_ContactOperate {
            get {
                return ResourceManager.GetString("CDDEAGroup_LS_ContactOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Cycle 종료(유효 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_LS_CycleEnd_Msg1 {
            get {
                return ResourceManager.GetString("CDDEAGroup_LS_CycleEnd_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Cycle 종료(유효)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_LS_CycleEnd_Msg2 {
            get {
                return ResourceManager.GetString("CDDEAGroup_LS_CycleEnd_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Cycle 종료(무효 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_LS_CycleEnd_Msg3 {
            get {
                return ResourceManager.GetString("CDDEAGroup_LS_CycleEnd_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Cycle 종료(무효)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_LS_CycleEnd_Msg4 {
            get {
                return ResourceManager.GetString("CDDEAGroup_LS_CycleEnd_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 수집 분석 중 문제 발생(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_LS_DoThreadWork_Msg {
            get {
                return ResourceManager.GetString("CDDEAGroup_LS_DoThreadWork_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh 주소가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_NoneRefreshAddress {
            get {
                return ResourceManager.GetString("CDDEAGroup_NoneRefreshAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///    번들 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_NormalBundleListCount_Msg {
            get {
                return ResourceManager.GetString("CDDEAGroup_NormalBundleListCount_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Packet 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_PackerInfo_Msg1 {
            get {
                return ResourceManager.GetString("CDDEAGroup_PackerInfo_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipe가 일치합니다. 기준접점 수집을 시작합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_RecipeMatch {
            get {
                return ResourceManager.GetString("CDDEAGroup_RecipeMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Cycle 종료(유효 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_sFilterNormalCycle_End_Msg1 {
            get {
                return ResourceManager.GetString("CDDEAGroup_sFilterNormalCycle_End_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Cycle 종료(유효)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_sFilterNormalCycle_End_Msg2 {
            get {
                return ResourceManager.GetString("CDDEAGroup_sFilterNormalCycle_End_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Cycle 종료(무효 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_sFilterNormalCycle_End_Msg3 {
            get {
                return ResourceManager.GetString("CDDEAGroup_sFilterNormalCycle_End_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Cycle 종료(무효)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_sFilterNormalCycle_End_Msg4 {
            get {
                return ResourceManager.GetString("CDDEAGroup_sFilterNormalCycle_End_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] Bit분석 중 오류 (과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEAGroup_WriteFragBitLogS_Exception_Msg {
            get {
                return ResourceManager.GetString("CDDEAGroup_WriteFragBitLogS_Exception_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 수집 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectData_Msg1 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectData_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 수집 재시도(0x10A0005) (과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectData_Msg10 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectData_Msg10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] PLC 통신 중 재시도 20회 시도후 에러 지속발생(0x10A0005)으로 정지(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectData_Msg11 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectData_Msg11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 수집 재시도(0x10A0006) (과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectData_Msg12 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectData_Msg12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] PLC 통신 중 재시도 20회 시도후 에러 지속발생(0x10A0006)으로 정지(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectData_Msg13 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectData_Msg13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 수집 재시도(0x1808505) (과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectData_Msg14 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectData_Msg14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] PLC 통신 중 재시도 20회 시도후 에러 지속발생(0x1808505)으로 정지(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectData_Msg15 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectData_Msg15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] PLC Connection 끊김으로 인해 수집 종료 (과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectData_Msg16 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectData_Msg16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 수집 재시도(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectData_Msg17 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectData_Msg17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] PLC 통신 중 재시도 20 회 시도후 에러 지속발생(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectData_Msg18 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectData_Msg18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   으로 정지(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectData_Msg19 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectData_Msg19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 수집 재시도(0x1808504) (과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectData_Msg2 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectData_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] PLC 통신 중 재시도 20회 시도후 에러 지속발생(0x1808504)으로 정지(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectData_Msg3 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectData_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 수집 재시도(0x10A0002) (과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectData_Msg4 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectData_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] PLC 통신 중 재시도 20회 시도후 에러 지속발생(0x10A0002)으로 정지(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectData_Msg5 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectData_Msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 수집 재시도(0x10A0003) (과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectData_Msg6 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectData_Msg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] PLC 통신 중 재시도 20회 시도후 에러 지속발생(0x10A0003)으로 정지(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectData_Msg7 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectData_Msg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 수집 재시도(0x10A0004) (과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectData_Msg8 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectData_Msg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] PLC 통신 중 재시도 20회 시도후 에러 지속발생(0x10A0004)으로 정지(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectData_Msg9 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectData_Msg9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 파라메터 수집 진행과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectLOBData_Msg1 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectLOBData_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 파라메터 수집 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectLOBData_Msg2 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectLOBData_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 수집 재시도(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectLOBData_Msg3 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectLOBData_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] PLC 통신 중 에러 발생 정지(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectLOBData_Msg4 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectLOBData_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectLOBData_Msg5 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectLOBData_Msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회 재시도(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectLOBData_Msg6 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectLOBData_Msg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 파라미터 수집 안됨과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectLOBData_Msg7 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectLOBData_Msg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 파라미터 없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_CollectLOBData_Msg8 {
            get {
                return ResourceManager.GetString("CDDEARead_CollectLOBData_Msg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 부분수집 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Dowork_LS_Msg1 {
            get {
                return ResourceManager.GetString("CDDEARead_Dowork_LS_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 필터수집 종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Dowork_LS_Msg10 {
            get {
                return ResourceManager.GetString("CDDEARead_Dowork_LS_Msg10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 현재패킷(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Dowork_LS_Msg11 {
            get {
                return ResourceManager.GetString("CDDEARead_Dowork_LS_Msg11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   번 인덱스패킷)에 남아있는 수집대상접점이 없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Dowork_LS_Msg12 {
            get {
                return ResourceManager.GetString("CDDEARead_Dowork_LS_Msg12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 필터수집 종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Dowork_LS_Msg13 {
            get {
                return ResourceManager.GetString("CDDEARead_Dowork_LS_Msg13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] LS Monitor Items의 Buffer Size :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Dowork_LS_Msg14 {
            get {
                return ResourceManager.GetString("CDDEARead_Dowork_LS_Msg14", resourceCulture);
            }
        }
        
        /// <summary>
        ///    =&gt; 100 미만으로 설정해 주십시오.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Dowork_LS_Msg15 {
            get {
                return ResourceManager.GetString("CDDEARead_Dowork_LS_Msg15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] LS PLC 수집 실행 실패!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Dowork_LS_Msg16 {
            get {
                return ResourceManager.GetString("CDDEARead_Dowork_LS_Msg16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] LS 수집중 문제 발생(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Dowork_LS_Msg17 {
            get {
                return ResourceManager.GetString("CDDEARead_Dowork_LS_Msg17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 전체수집 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Dowork_LS_Msg2 {
            get {
                return ResourceManager.GetString("CDDEARead_Dowork_LS_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 출력수집 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Dowork_LS_Msg3 {
            get {
                return ResourceManager.GetString("CDDEARead_Dowork_LS_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] LOB수집 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Dowork_LS_Msg4 {
            get {
                return ResourceManager.GetString("CDDEARead_Dowork_LS_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 필터수집 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Dowork_LS_Msg5 {
            get {
                return ResourceManager.GetString("CDDEARead_Dowork_LS_Msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 파라미터 수집 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Dowork_LS_Msg6 {
            get {
                return ResourceManager.GetString("CDDEARead_Dowork_LS_Msg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 물리적으로 필터수집이 정상적으로 되지 않아 종료합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Dowork_LS_Msg7 {
            get {
                return ResourceManager.GetString("CDDEARead_Dowork_LS_Msg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] LS PLC 수집 실행!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Dowork_LS_Msg8 {
            get {
                return ResourceManager.GetString("CDDEARead_Dowork_LS_Msg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 전체 수집 Packet 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Dowork_LS_Msg9 {
            get {
                return ResourceManager.GetString("CDDEARead_Dowork_LS_Msg9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 부분수집 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_DoWork_Msg1 {
            get {
                return ResourceManager.GetString("CDDEARead_DoWork_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Packet 번호 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_DoWork_Msg10 {
            get {
                return ResourceManager.GetString("CDDEARead_DoWork_Msg10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Cycle 번호 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_DoWork_Msg11 {
            get {
                return ResourceManager.GetString("CDDEARead_DoWork_Msg11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 레시피 변경으로 수집 대기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_DoWork_Msg12 {
            get {
                return ResourceManager.GetString("CDDEARead_DoWork_Msg12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 전체수집 종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_DoWork_Msg13 {
            get {
                return ResourceManager.GetString("CDDEARead_DoWork_Msg13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 출력수집 종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_DoWork_Msg14 {
            get {
                return ResourceManager.GetString("CDDEARead_DoWork_Msg14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 필터수집 종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_DoWork_Msg15 {
            get {
                return ResourceManager.GetString("CDDEARead_DoWork_Msg15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 현재패킷(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_DoWork_Msg16 {
            get {
                return ResourceManager.GetString("CDDEARead_DoWork_Msg16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   번 인덱스패킷)에 남아있는 수집대상접점이 없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_DoWork_Msg17 {
            get {
                return ResourceManager.GetString("CDDEARead_DoWork_Msg17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 부분수집 종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_DoWork_Msg18 {
            get {
                return ResourceManager.GetString("CDDEARead_DoWork_Msg18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 수집중 문제 발생(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_DoWork_Msg19 {
            get {
                return ResourceManager.GetString("CDDEARead_DoWork_Msg19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 전체수집 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_DoWork_Msg2 {
            get {
                return ResourceManager.GetString("CDDEARead_DoWork_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 출력수집 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_DoWork_Msg3 {
            get {
                return ResourceManager.GetString("CDDEARead_DoWork_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] LOB수집 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_DoWork_Msg4 {
            get {
                return ResourceManager.GetString("CDDEARead_DoWork_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 필터수집 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_DoWork_Msg5 {
            get {
                return ResourceManager.GetString("CDDEARead_DoWork_Msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 파라미터 수집 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_DoWork_Msg6 {
            get {
                return ResourceManager.GetString("CDDEARead_DoWork_Msg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 수집 초기 Packet 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_DoWork_Msg7 {
            get {
                return ResourceManager.GetString("CDDEARead_DoWork_Msg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 수집 초기 Packet 번호 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_DoWork_Msg8 {
            get {
                return ResourceManager.GetString("CDDEARead_DoWork_Msg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 기준접점 수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_DoWork_Msg9 {
            get {
                return ResourceManager.GetString("CDDEARead_DoWork_Msg9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   필터수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_FolderNameF {
            get {
                return ResourceManager.GetString("CDDEARead_FolderNameF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   부분수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_FolderNameP {
            get {
                return ResourceManager.GetString("CDDEARead_FolderNameP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] PLC 연결 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Start_Msg1 {
            get {
                return ResourceManager.GetString("CDDEARead_Start_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    =&gt; 100 미만으로 설정해 주십시오.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Start_Msg10 {
            get {
                return ResourceManager.GetString("CDDEARead_Start_Msg10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] LS Monitoring Item 등록 실패!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Start_Msg11 {
            get {
                return ResourceManager.GetString("CDDEARead_Start_Msg11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] LS Monitor Items Buffer Size :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Start_Msg12 {
            get {
                return ResourceManager.GetString("CDDEARead_Start_Msg12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] LS Monitoring Item 등록 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Start_Msg13 {
            get {
                return ResourceManager.GetString("CDDEARead_Start_Msg13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계산 중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Start_Msg14 {
            get {
                return ResourceManager.GetString("CDDEARead_Start_Msg14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   부분수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Start_Msg2 {
            get {
                return ResourceManager.GetString("CDDEARead_Start_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   필터수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Start_Msg3 {
            get {
                return ResourceManager.GetString("CDDEARead_Start_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파라미터수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Start_Msg4 {
            get {
                return ResourceManager.GetString("CDDEARead_Start_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 수집 분석 프로세스 중 오류 발생과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Start_Msg5 {
            get {
                return ResourceManager.GetString("CDDEARead_Start_Msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] LS PLC 연결 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Start_Msg6 {
            get {
                return ResourceManager.GetString("CDDEARead_Start_Msg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 필터링 된 전체 Buffer Size : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Start_Msg7 {
            get {
                return ResourceManager.GetString("CDDEARead_Start_Msg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 필터링 된 전체 접점 리스트 Log Csv 경로 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Start_Msg8 {
            get {
                return ResourceManager.GetString("CDDEARead_Start_Msg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] LS Monitor Items의 Buffer Size :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Start_Msg9 {
            get {
                return ResourceManager.GetString("CDDEARead_Start_Msg9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 정지하기 위해 남은 정보 처리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Stop_Msg1 {
            get {
                return ResourceManager.GetString("CDDEARead_Stop_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 남은 Queue 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Stop_Msg2 {
            get {
                return ResourceManager.GetString("CDDEARead_Stop_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 정지 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_Stop_Msg3 {
            get {
                return ResourceManager.GetString("CDDEARead_Stop_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 필터수집 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_UEventCycleChanged_Msg1 {
            get {
                return ResourceManager.GetString("CDDEARead_UEventCycleChanged_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Cycle 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_UEventCycleChanged_Msg2 {
            get {
                return ResourceManager.GetString("CDDEARead_UEventCycleChanged_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Packet 번호 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_UEventCycleChanged_Msg3 {
            get {
                return ResourceManager.GetString("CDDEARead_UEventCycleChanged_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Cycle 번호 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_UEventCycleChanged_Msg4 {
            get {
                return ResourceManager.GetString("CDDEARead_UEventCycleChanged_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 재실행 PLC Connection 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_UEventCycleTimeOut_Msg {
            get {
                return ResourceManager.GetString("CDDEARead_UEventCycleTimeOut_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Cycle 범위 조건 충족 못함과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_UEventFragMasterSwitch_Msg1 {
            get {
                return ResourceManager.GetString("CDDEARead_UEventFragMasterSwitch_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 기준접점 수집 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_UEventFragMasterSwitch_Msg2 {
            get {
                return ResourceManager.GetString("CDDEARead_UEventFragMasterSwitch_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 전체수집 진행과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_UEventFragMasterSwitch_Msg3 {
            get {
                return ResourceManager.GetString("CDDEARead_UEventFragMasterSwitch_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 전체 Packet 수 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_UEventFragMasterSwitch_Msg4 {
            get {
                return ResourceManager.GetString("CDDEARead_UEventFragMasterSwitch_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Cycle 종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_UEventFragMasterSwitch_Msg5 {
            get {
                return ResourceManager.GetString("CDDEARead_UEventFragMasterSwitch_Msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 기준접점 수집 마지막 Packet과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_UEventFragMasterSwitch_Msg6 {
            get {
                return ResourceManager.GetString("CDDEARead_UEventFragMasterSwitch_Msg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] Packet전환 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_UEventFragMasterSwitch_Msg7 {
            get {
                return ResourceManager.GetString("CDDEARead_UEventFragMasterSwitch_Msg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 수집 전 Packet별 수집 테스트 진행(1회)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_VerifyBlock_Msg1 {
            get {
                return ResourceManager.GetString("CDDEARead_VerifyBlock_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 수집 대상 Packet Count = 0, 수집 대상 접점이 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_VerifyBlock_Msg2 {
            get {
                return ResourceManager.GetString("CDDEARead_VerifyBlock_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 번째 패킷 실패 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_VerifyBlock_Msg3 {
            get {
                return ResourceManager.GetString("CDDEARead_VerifyBlock_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_VerifyBlock_Msg4 {
            get {
                return ResourceManager.GetString("CDDEARead_VerifyBlock_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수집 불가 접점 : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_VerifyBlock_Msg5 {
            get {
                return ResourceManager.GetString("CDDEARead_VerifyBlock_Msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEARead_VerifyBlock_Msg6 {
            get {
                return ResourceManager.GetString("CDDEARead_VerifyBlock_Msg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 로그 기록 중지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEATask_BeforeStop_Msg {
            get {
                return ResourceManager.GetString("CDDEATask_BeforeStop_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEATask_CreateCSV_Msg1 {
            get {
                return ResourceManager.GetString("CDDEATask_CreateCSV_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   출력수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEATask_CreateCSV_Msg2 {
            get {
                return ResourceManager.GetString("CDDEATask_CreateCSV_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   필터수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEATask_CreateCSV_Msg3 {
            get {
                return ResourceManager.GetString("CDDEATask_CreateCSV_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파라미터수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEATask_CreateCSV_Msg4 {
            get {
                return ResourceManager.GetString("CDDEATask_CreateCSV_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   부분수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEATask_CreateCSV_Msg5 {
            get {
                return ResourceManager.GetString("CDDEATask_CreateCSV_Msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 파일 생성 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEATask_CreateCSV_Msg6 {
            get {
                return ResourceManager.GetString("CDDEATask_CreateCSV_Msg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류]  파일 생성 중 문제 발생(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEATask_CreateCSV_Msg7 {
            get {
                return ResourceManager.GetString("CDDEATask_CreateCSV_Msg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 파일 생성 오류 (과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEATask_CreateXml_Msg1 {
            get {
                return ResourceManager.GetString("CDDEATask_CreateXml_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [정보] 파일 생성 (과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEATask_CreateXml_Msg2 {
            get {
                return ResourceManager.GetString("CDDEATask_CreateXml_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 파일 생성 중 문제 발생(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEATask_CreateXml_Msg3 {
            get {
                return ResourceManager.GetString("CDDEATask_CreateXml_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 로그 기록 중 문제가 발생(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CDDEATask_DoThreadWork_Msg {
            get {
                return ResourceManager.GetString("CDDEATask_DoThreadWork_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DDEA_None {
            get {
                return ResourceManager.GetString("DDEA_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1. 기본통신설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelConfig_Defaultcommunicationsetting {
            get {
                return ResourceManager.GetString("UCChannelConfig_Defaultcommunicationsetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2. 상세통신설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelConfig_Detailedcommunicationsetting {
            get {
                return ResourceManager.GetString("UCChannelConfig_Detailedcommunicationsetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelConfig_Msg_GetConfig {
            get {
                return ResourceManager.GetString("UCChannelConfig_Msg_GetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I/O Address는 16진수를 입력하세요.(ex: 03FF )과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelConfig_Msg_SetConfig {
            get {
                return ResourceManager.GetString("UCChannelConfig_Msg_SetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정할 내용이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelConfig_Msg_Thereisnothingtoset {
            get {
                return ResourceManager.GetString("UCChannelConfig_Msg_Thereisnothingtoset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network No입력, 1이상입력가능과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelConfig_NetworkNoinput {
            get {
                return ResourceManager.GetString("UCChannelConfig_NetworkNoinput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3. 기타설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelConfig_Othercommunicationsetting {
            get {
                return ResourceManager.GetString("UCChannelConfig_Othercommunicationsetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - PC 측 설정 -과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelConfig_PCsidesettings {
            get {
                return ResourceManager.GetString("UCChannelConfig_PCsidesettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - PLC 측 설정 -과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelConfig_PLCsidesettings {
            get {
                return ResourceManager.GetString("UCChannelConfig_PLCsidesettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Station No 입력, 1이상 입력 가능과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelConfig_StationNoinput {
            get {
                return ResourceManager.GetString("UCChannelConfig_StationNoinput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영역별 한계 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_AreaLimitInformation {
            get {
                return ResourceManager.GetString("UCChannelTest_AreaLimitInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수집 주소 입력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_CollectionAddressInput {
            get {
                return ResourceManager.GetString("UCChannelTest_CollectionAddressInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수집 진행 내용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_CollectionProgress {
            get {
                return ResourceManager.GetString("UCChannelTest_CollectionProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결 테스트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Connectiontest {
            get {
                return ResourceManager.GetString("UCChannelTest_Connectiontest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수동 테스트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Manualtest {
            get {
                return ResourceManager.GetString("UCChannelTest_Manualtest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력된 접점이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Msg_btnEasyCollectStart {
            get {
                return ResourceManager.GetString("UCChannelTest_Msg_btnEasyCollectStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   간편 수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Msg_btnEasyCollectStopGuid1 {
            get {
                return ResourceManager.GetString("UCChannelTest_Msg_btnEasyCollectStopGuid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그를 저장하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Msg_btnEasyCollectStopGuid2 {
            get {
                return ResourceManager.GetString("UCChannelTest_Msg_btnEasyCollectStopGuid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   간편 수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Msg_btnEasyCollectStopGuid3 {
            get {
                return ResourceManager.GetString("UCChannelTest_Msg_btnEasyCollectStopGuid3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결 실패
        ///통신 설정을 확인하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Msg_Connect {
            get {
                return ResourceManager.GetString("UCChannelTest_Msg_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해제 실패
        ///통신 설정을 확인하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Msg_Disconnect {
            get {
                return ResourceManager.GetString("UCChannelTest_Msg_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력된 접점이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Msg_ReadManualDataGuid1 {
            get {
                return ResourceManager.GetString("UCChannelTest_Msg_ReadManualDataGuid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   간편 수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Msg_ReadManualDataGuid2 {
            get {
                return ResourceManager.GetString("UCChannelTest_Msg_ReadManualDataGuid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error가 10번이상 발생하여 정지합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Msg_ReadManualDataGuid3 {
            get {
                return ResourceManager.GetString("UCChannelTest_Msg_ReadManualDataGuid3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력된 접점이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Msg_ReadManualGuid1 {
            get {
                return ResourceManager.GetString("UCChannelTest_Msg_ReadManualGuid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   간편 수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Msg_ReadManualGuid2 {
            get {
                return ResourceManager.GetString("UCChannelTest_Msg_ReadManualGuid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정된 PLC 통신 정보로 통신 연결 테스트 진행과
        ///PLC의 각종 정보를 확인합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Msg_TestHelp1 {
            get {
                return ResourceManager.GetString("UCChannelTest_Msg_TestHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정된 PLC 통신 정보로 통신 연결 후 수집 주소 입력 창에
        ///등록된 접점을 수집합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Msg_TestHelp2 {
            get {
                return ResourceManager.GetString("UCChannelTest_Msg_TestHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력된 접점이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Msg_TestLSChannelGuid1 {
            get {
                return ResourceManager.GetString("UCChannelTest_Msg_TestLSChannelGuid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   간편 수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Msg_TestLSChannelGuid2 {
            get {
                return ResourceManager.GetString("UCChannelTest_Msg_TestLSChannelGuid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test Monitoring Item 등록 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Msg_TestLSChannelGuid3 {
            get {
                return ResourceManager.GetString("UCChannelTest_Msg_TestLSChannelGuid3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수집 실패 Error Code : {0} Count = {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Msg_TestMitsuChannelGuid1 {
            get {
                return ResourceManager.GetString("UCChannelTest_Msg_TestMitsuChannelGuid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수집 테스트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Msg_TestMitsuChannelGuid2 {
            get {
                return ResourceManager.GetString("UCChannelTest_Msg_TestMitsuChannelGuid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLC 스캔 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_ScanplcInformation {
            get {
                return ResourceManager.GetString("UCChannelTest_ScanplcInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   간편수집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_SimpleCollection {
            get {
                return ResourceManager.GetString("UCChannelTest_SimpleCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시 작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Start {
            get {
                return ResourceManager.GetString("UCChannelTest_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLC 상태 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_StateplcInformation {
            get {
                return ResourceManager.GetString("UCChannelTest_StateplcInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정 지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Stop {
            get {
                return ResourceManager.GetString("UCChannelTest_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테스트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCChannelTest_Test {
            get {
                return ResourceManager.GetString("UCChannelTest_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수집 주소 입력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectionTest_CollectionAddressInput {
            get {
                return ResourceManager.GetString("UCConnectionTest_CollectionAddressInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수집 주기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectionTest_CollectionCycle {
            get {
                return ResourceManager.GetString("UCConnectionTest_CollectionCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수집 진행 내용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectionTest_CollectionProgress {
            get {
                return ResourceManager.GetString("UCConnectionTest_CollectionProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectionTest_Connect {
            get {
                return ResourceManager.GetString("UCConnectionTest_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연속 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectionTest_Continuousstart {
            get {
                return ResourceManager.GetString("UCConnectionTest_Continuousstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수동 테스트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectionTest_Manualtest {
            get {
                return ResourceManager.GetString("UCConnectionTest_Manualtest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모니터 제어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectionTest_Monitorcontrol {
            get {
                return ResourceManager.GetString("UCConnectionTest_Monitorcontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결 실패
        ///통신 설정을 확인하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectionTest_Msg_btnConnect {
            get {
                return ResourceManager.GetString("UCConnectionTest_Msg_btnConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해제 실패
        ///통신 설정을 확인하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectionTest_Msg_btnDisConnect {
            get {
                return ResourceManager.GetString("UCConnectionTest_Msg_btnDisConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대기 시간이 없이 수집 후 바로 다시 명령을 보냄과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectionTest_Msg_ConnectionTestHelp1 {
            get {
                return ResourceManager.GetString("UCConnectionTest_Msg_ConnectionTestHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error가 10번이상 발생하여 정지합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectionTest_Msg_ReadSelfData {
            get {
                return ResourceManager.GetString("UCConnectionTest_Msg_ReadSelfData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수집 실패 Error Code : {0} Count = {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectionTest_Msg_tmrPlcInfoStart {
            get {
                return ResourceManager.GetString("UCConnectionTest_Msg_tmrPlcInfoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLC 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectionTest_PLCInformation {
            get {
                return ResourceManager.GetString("UCConnectionTest_PLCInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectionTest_Start {
            get {
                return ResourceManager.GetString("UCConnectionTest_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectionTest_Stop {
            get {
                return ResourceManager.GetString("UCConnectionTest_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectionTest_Uncheck {
            get {
                return ResourceManager.GetString("UCConnectionTest_Uncheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectSetting_Msg_GetConfig {
            get {
                return ResourceManager.GetString("UCConnectSetting_Msg_GetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I/O Address는 16진수를 입력하세요.(ex: 03FF )과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectSetting_Msg_SetConfig {
            get {
                return ResourceManager.GetString("UCConnectSetting_Msg_SetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CCLink 선택시 IO Address 입력, 저장후 수집가능, 설정 정보 Open시 초기화됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectSetting_MsgConnectionSettingHelp1 {
            get {
                return ResourceManager.GetString("UCConnectSetting_MsgConnectionSettingHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network No입력, 1이상입력가능과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectSetting_MsgConnectionSettingHelp2 {
            get {
                return ResourceManager.GetString("UCConnectSetting_MsgConnectionSettingHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Station No 입력, 1이상 입력 가능과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectSetting_MsgConnectionSettingHelp3 {
            get {
                return ResourceManager.GetString("UCConnectSetting_MsgConnectionSettingHelp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect Type 상세 통신 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectSetting_MsgConnectionSettingHelp4 {
            get {
                return ResourceManager.GetString("UCConnectSetting_MsgConnectionSettingHelp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정할 내용이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectSetting_MsgConnectionSettingHelp5 {
            get {
                return ResourceManager.GetString("UCConnectSetting_MsgConnectionSettingHelp5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PC와 연결된 PLC 기본 통신설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCConnectSetting_MsgConnectionSettingHelp6 {
            get {
                return ResourceManager.GetString("UCConnectSetting_MsgConnectionSettingHelp6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   접점과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UCMultiStepTagTable_Msg_mnuSelectItemDisplay {
            get {
                return ResourceManager.GetString("UCMultiStepTagTable_Msg_mnuSelectItemDisplay", resourceCulture);
            }
        }
    }
}
